version: 2

# Extra formats
# PDF generation is failing for now; disabled on 2020-12-02
#formats:
#  - pdf

# Build documentation
sphinx:
  configuration: docs/conf.py

python:
  # make sure we're using Python 3
  version: 3
  install:
    - requirements: docs/requirements.txt
