#! /bin/bash

cwd=$(pwd)
cd ~/MOM6_OBGC_examples/src/ocean_BGC/generic_tracers

cobaltbuild

for eta in {0..10..2}
do
	sed -i "s/call g_tracer_add_param('eta', mixo(1)%eta, .*)/call g_tracer_add_param('eta', mixo(1)%eta, 0.1\*$eta)/" generic_COBALT.F90
	multiyear "eta${eta}year" 2
done

cd $cwd
