#! /bin/bash

cwd=$(pwd)
cd ~/MOM6_OBGC_examples/src/ocean_BGC/generic_tracers

cobaltbuild

sed -i "s/call g_tracer_add_param('nu', mixo(1)%nu, .*)/call g_tracer_add_param('nu', mixo(1)%nu, 0.0)/" generic_COBALT.F90

for eps in {0..10}
do
	sed -i "s/call g_tracer_add_param('psi_static', mixo(1)%psi_static, .*)/call g_tracer_add_param('psi_static', mixo(1)%psi_static, 0.1\*$eps)/" generic_COBALT.F90
	multiyear "$1${eps}year" 2
done

cd $cwd
